UPPW-53: user authorization for rating API
pascal-lise/uebungsprojekt pull request #10
Opened 2022-05-31 12:34 UTC by pascalise

2022-06-09 12:43 UTC, maximilianbuttlies requested changes

2022-06-09 12:43 UTC, maximilianbuttlies commented on frontend/src/pages/GameDetailPage.tsx
> +    if(game && auth.user?.access_token) {
Und was wenn kein Access Token da ist?

2022-06-09 12:43 UTC, maximilianbuttlies commented on frontend/src/api/GamesApi.ts
> +        return (await axios.post(
Du kannst axios so konfigurieren das immer der Token mitgeschickt wird, wenn einer vorhanden ist.  https://stackoverflow.com/a/55259078/13166262

2022-06-10 09:48 UTC, pascalise commented on frontend/src/pages/GameDetailPage.tsx
> +    if(game && auth.user?.access_token) {
Dann kann keine Bewertung abgegeben werden, s. [line 65](https://github.com/pascalise/uebungsprojekt/blob/UPPW-54-user-rating/frontend/src/pages/GameDetailPage.tsx#L65)

2022-06-29 09:00 UTC, dominikalexanderlise requested changes, later dismissed

2022-06-29 09:00 UTC, ghost commented on frontend/src/model/Rating.ts
> +    ratedBy: string | undefined
Gibt es einen Grund, warum du mal `null` und mal `undefined` nutzt?

2022-06-29 09:00 UTC, ghost commented on frontend/src/pages/GameDetailPage.tsx
> +  }, [game, auth.user])
Eines meiner größten Learnings seit ich React programmiere ist, dass useEffect generell mit Vorsicht zu genießen ist. 

Mir ist es immer wieder passiert, dass ich Endlosschleifen erzeugt habe, da ein useEffect einen State gesetzt hat, der eine Abhängigkeit eines anderen useEffects war, der wieder einen state geändert hat, usw.

Oder mir sind states out of sync geraten, weil ich quasi einen derived state nicht immer konsequent geupdatet habe.

Thomas hat mir mal erklärt, dass es eigentlich bei useState rein um Seiteneffekte bzw eigentlich sogar nur Synchronisierung gehen sollte und seit dem gucke ich, wenn ich in Versuchung gerate useEffect zu nutzen, irgendwie genauer hin und finde oft eine bessere Lösung.

David hat neulich in Teams gepostet (ich hab's ehrlich gesagt noch nicht gelesen, aber habe es fest vor): https://beta.reactjs.org/learn/you-might-not-need-an-effect

Und für derived state kann ich diesen Post empfehlen: https://blog.webdevsimplified.com/2019-11/never-store-derived-state/
Oder ganz frisch in Videoform: https://www.youtube.com/watch?v=tz0fDABt67g&ab_channel=WebDevSimplified

2022-06-29 09:00 UTC, dominikalexanderlise commented on frontend/src/pages/GameDetailPage.tsx
> +  }, [state])
Ich weiß nicht genau, wie/wo du den location.state setzt. Ich kann mir vorstellen, dass das hier eigentlich unnötig ist. Wir können gerne noch mal zusammen drübergucken, ruf mich gerne einfach an, wenn du Zeit hast.

2022-07-08 11:41 UTC, pascalise commented on frontend/src/pages/GameDetailPage.tsx
> +  }, [game, auth.user])
Danke für die vielen Tipps und Links! Ich würde das useEffect erstmal so lassen wollen, da es mir auch von Franz für diesen Zweck introduced wurde. Würde deine Empfehlungen gerne mal separat behandeln, aufgrund meiner fehlenden Zeit fürs ÜP würde ich aber den Fortschritt in der Ticketbearbeitung erstmal vorziehen, bevor es ins Refactoring geht.

2022-07-08 11:41 UTC, pascalise commented on frontend/src/model/Rating.ts
> +    ratedBy: string | undefined
Wird angepasst.

2022-07-27 07:24 UTC, dominikalexanderlise approved these changes

2022-07-27 07:24 UTC, dominikalexanderlise commented on frontend/src/api/Axios.ts
> +export default axiosService
👍

2022-07-27 07:24 UTC, dominikalexanderlise commented on frontend/src/config/axiosConfig.ts
> +}
👍 nice, das kannte ich gar nicht. Ist ja super handy!

2022-07-27 07:24 UTC, dominikalexanderlise commented on frontend/src/layouts/Header.tsx
> +
Der Code wäre vielleicht in der Main Komponente oder vielleicht sogar einer eigenen Auth-Komponente um die Main Komponente etwas besser aufgehoben.

2022-07-27 07:24 UTC, dominikalexanderlise commented on frontend/src/pages/GameDetailPage.tsx
> +  const [graphics, setGraphics] = useState<number>(1)
Nur zur Info: Wenn null nicht erlaubt ist, dann kannst du die generic-Klammern <> sogar komplett weglassen.

2022-07-27 07:38 UTC, merged